import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'data/open_backend.dart';
import 'main.dart' as ui;
import 'real_app_shell.dart';

class DirectOpenApp extends StatelessWidget{const DirectOpenApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Open',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:Colors.white,colorScheme:ColorScheme.fromSeed(seedColor:ui.OpenApp.lime),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:ui.OpenApp.soft,border:OutlineInputBorder(borderRadius:BorderRadius.circular(22),borderSide:BorderSide.none),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(22),borderSide:BorderSide.none),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(22),borderSide:const BorderSide(color:ui.OpenApp.lime,width:2)),contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:17)),filledButtonTheme:FilledButtonThemeData(style:FilledButton.styleFrom(backgroundColor:ui.OpenApp.lime,foregroundColor:ui.OpenApp.ink,minimumSize:const Size.fromHeight(58),shape:const StadiumBorder(),textStyle:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)))),home:const _Splash());}
Widget _shell()=>Builder(builder:(context)=>RealAppShell(onSignedOut:()=>Navigator.of(context,rootNavigator:true).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const _Welcome()),(_)=>false)));
Future<void> _afterAuth(BuildContext context)async{final done=await OpenBackend.instance.hasCompletedProfile();if(!context.mounted)return;Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>done?_shell():const _ProfileScreen()),(_)=>false);}
String _phone(String v){var p=v.replaceAll(RegExp(r'\D'),'');if(p.startsWith('0'))p=p.substring(1);if(!p.startsWith('90'))p='90$p';return '+$p';}

class _Splash extends StatefulWidget{const _Splash();@override State<_Splash> createState()=>_SplashState();}
class _SplashState extends State<_Splash>{@override void initState(){super.initState();_go();}Future<void> _go()async{await Future.delayed(const Duration(milliseconds:800));if(!mounted)return;final u=OpenBackend.instance.client.auth.currentUser;if(u!=null&&u.isAnonymous){await OpenBackend.instance.signOut();}if(!mounted)return;if(OpenBackend.instance.isAuthenticated){try{final done=await OpenBackend.instance.hasCompletedProfile();if(!mounted)return;Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>done?_shell():const _ProfileScreen()));return;}catch(_){}}Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const _Welcome()));}@override Widget build(BuildContext context)=>const Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[ui.AppSvg(ui.AppIcons.splash,size:118,card:true),SizedBox(height:26),Text('Open',style:TextStyle(fontSize:44,fontWeight:FontWeight.w900))])));}

class _Welcome extends StatelessWidget{const _Welcome();@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Spacer(),const ui.AppSvg(ui.AppIcons.splash,size:90,card:true),const SizedBox(height:28),const Text('Open',style:TextStyle(fontSize:52,fontWeight:FontWeight.w900)),const SizedBox(height:18),const Text('Kaydırma.\nÖnce kilidimi aç.',style:TextStyle(fontSize:31,height:1.08,fontWeight:FontWeight.w800)),const Spacer(),FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const _Onboarding())),child:const Text('Kayıt ol')),const SizedBox(height:10),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const _LoginScreen())),child:const Center(child:Text('Zaten hesabın var mı? Giriş yap',style:TextStyle(color:ui.OpenApp.ink,fontWeight:FontWeight.w800))))]))));}

class _Onboarding extends StatefulWidget{const _Onboarding();@override State<_Onboarding> createState()=>_OnboardingState();}
class _OnboardingState extends State<_Onboarding>{final controller=PageController();int page=0;final pages=const [('Profil değil,\ninsanı keşfet.','Önce soruları cevapla, sonra karar ver.',ui.AppIcons.lock),('3 kilit soru,\nyüzlerce olasılık.','Merak uyandıran sorularla daha anlamlı sohbetler.',ui.AppIcons.question),('Doğru kişiyle\nanahtarın uyusun.','Anahtarını gönder. Kabul edilirse profil açılır.',ui.AppIcons.key),('Gerçek bağlantılar\nburada başlar.','Daha az yüzeysel, daha çok sen.',ui.AppIcons.unlock)];void next(){if(page<3){controller.nextPage(duration:const Duration(milliseconds:300),curve:Curves.easeOutCubic);}else{Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const _RegisterScreen()));}}@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[Align(alignment:Alignment.centerRight,child:Padding(padding:const EdgeInsets.only(right:18),child:TextButton(onPressed:()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const _RegisterScreen())),child:const Text('Atla')))),Expanded(child:PageView.builder(controller:controller,itemCount:pages.length,onPageChanged:(v)=>setState(()=>page=v),itemBuilder:(_,i){final x=pages[i];return Padding(padding:const EdgeInsets.fromLTRB(28,6,28,24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Center(child:ui.AppSvg(x.$3,size:150,card:true))),Text(x.$1,style:const TextStyle(fontSize:34,height:1.05,fontWeight:FontWeight.w900)),const SizedBox(height:12),Text(x.$2,style:const TextStyle(color:ui.OpenApp.muted,fontSize:16)),const SizedBox(height:20),FilledButton(onPressed:next,child:Text(i==3?'Hadi başlayalım':'Devam et'))]));}))])));}

class _RegisterScreen extends StatefulWidget{const _RegisterScreen();@override State<_RegisterScreen> createState()=>_RegisterScreenState();}
class _RegisterScreenState extends State<_RegisterScreen>{final email=TextEditingController(),password=TextEditingController(),phone=TextEditingController();bool phoneMode=true,busy=false;String? error;Future<void> emailGo()async{if(!RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$').hasMatch(email.text.trim())||password.text.length<6){setState(()=>error='Geçerli e-posta ve en az 6 karakter şifre gir.');return;}setState((){busy=true;error=null;});try{final r=await OpenBackend.instance.registerEmail(email.text,password.text);if(r.session==null){setState(()=>error='E-posta doğrulaması gerekiyor.');return;}if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const _ProfileScreen()),(_)=>false);}catch(e){if(mounted)setState(()=>error='Kayıt oluşturulamadı: $e');}finally{if(mounted)setState(()=>busy=false);}}void phoneGo(){if(phone.text.replaceAll(RegExp(r'\D'),'').length<10){setState(()=>error='Geçerli telefon numarası gir.');return;}Navigator.push(context,MaterialPageRoute(builder:(_)=>_PhoneOtpScreen(phone:_phone(phone.text),registering:true)));}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent),body:SafeArea(child:Padding(padding:const EdgeInsets.all(26),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const ui.PageTitle('Hesabını oluştur.','Telefon numarası veya e-posta ile kayıt ol.'),const SizedBox(height:24),SegmentedButton<bool>(segments:const [ButtonSegment(value:true,label:Text('Telefon'),icon:Icon(Icons.phone_outlined)),ButtonSegment(value:false,label:Text('E-posta'),icon:Icon(Icons.mail_outline))],selected:{phoneMode},onSelectionChanged:(v)=>setState(()=>phoneMode=v.first)),const SizedBox(height:22),if(phoneMode)TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Telefon numarası',prefixText:'+90 '))else...[TextField(controller:email,decoration:const InputDecoration(labelText:'E-posta')),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Şifre'))],if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:Colors.red))),const Spacer(),FilledButton(onPressed:busy?null:(phoneMode?phoneGo:emailGo),child:Text(busy?'Hesap oluşturuluyor...':phoneMode?'Kodu gönder':'Kayıt ol'))]))));}

class _LoginScreen extends StatefulWidget{const _LoginScreen();@override State<_LoginScreen> createState()=>_LoginScreenState();}
class _LoginScreenState extends State<_LoginScreen>{final email=TextEditingController(),password=TextEditingController(),phone=TextEditingController();bool phoneMode=false,busy=false;String? error;Future<void> login()async{setState(()=>busy=true);try{await OpenBackend.instance.loginEmail(email.text,password.text);if(mounted)await _afterAuth(context);}catch(_){if(mounted)setState(()=>error='E-posta veya şifre hatalı.');}finally{if(mounted)setState(()=>busy=false);}}void otp(){Navigator.push(context,MaterialPageRoute(builder:(_)=>_PhoneOtpScreen(phone:_phone(phone.text))));}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent),body:SafeArea(child:Padding(padding:const EdgeInsets.all(26),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const ui.PageTitle('Tekrar hoş geldin.','E-posta veya telefon numaranla giriş yap.'),const SizedBox(height:24),SegmentedButton<bool>(segments:const [ButtonSegment(value:false,label:Text('E-posta')),ButtonSegment(value:true,label:Text('Telefon'))],selected:{phoneMode},onSelectionChanged:(v)=>setState(()=>phoneMode=v.first)),const SizedBox(height:22),if(phoneMode)TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Telefon numarası',prefixText:'+90 '))else...[TextField(controller:email,decoration:const InputDecoration(labelText:'E-posta')),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Şifre'))],if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),const Spacer(),FilledButton(onPressed:busy?null:(phoneMode?otp:login),child:Text(phoneMode?'Kodu gönder':'Giriş yap'))]))));}

class _PhoneOtpScreen extends StatefulWidget{const _PhoneOtpScreen({required this.phone,this.registering=false});final String phone;final bool registering;@override State<_PhoneOtpScreen> createState()=>_PhoneOtpScreenState();}
class _PhoneOtpScreenState extends State<_PhoneOtpScreen>{final code=TextEditingController();bool busy=false;String? error;Future<void> go()async{if(code.text.trim()!='123456'){setState(()=>error='Kod hatalı. Test kodu: 123456');return;}setState(()=>busy=true);try{await OpenBackend.instance.verifyPhoneOtp(widget.phone,code.text);if(!mounted)return;if(widget.registering){Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const _ProfileScreen()),(_)=>false);}else{await _afterAuth(context);}}catch(e){if(mounted)setState(()=>error='Doğrulama yapılamadı: $e');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent),body:SafeArea(child:Padding(padding:const EdgeInsets.all(26),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ui.PageTitle('Kodu gir.','${widget.phone} için doğrulama kodunu yaz.'),const SizedBox(height:26),TextField(controller:code,keyboardType:TextInputType.number,maxLength:6,decoration:const InputDecoration(labelText:'Doğrulama kodu',helperText:'Şimdilik: 123456')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),const Spacer(),FilledButton(onPressed:busy?null:go,child:Text(busy?'Doğrulanıyor...':'Devam et'))]))));}

class _ProfileScreen extends StatefulWidget{const _ProfileScreen();@override State<_ProfileScreen> createState()=>_ProfileScreenState();}
class _ProfileScreenState extends State<_ProfileScreen>{
 final name=TextEditingController();String gender='Kadın';DateTime? birthDate;XFile? photo;bool busy=false,picking=false;String? error;
 int? get age{if(birthDate==null)return null;final n=DateTime.now();var a=n.year-birthDate!.year;if(n.month<birthDate!.month||(n.month==birthDate!.month&&n.day<birthDate!.day))a--;return a;}
 Future<void> pickPhoto()async{if(picking)return;setState(()=>picking=true);try{final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:88,maxWidth:1600);if(x!=null&&mounted)setState(()=>photo=x);}finally{if(mounted)setState(()=>picking=false);}}
 Future<void> pickBirth()async{final n=DateTime.now();final d=await showDatePicker(context:context,initialDate:birthDate??DateTime(n.year-25,n.month,n.day),firstDate:DateTime(1940),lastDate:DateTime(n.year-18,n.month,n.day),helpText:'Doğum tarihini seç');if(d!=null&&mounted)setState(()=>birthDate=d);}
 Future<void> next()async{if(photo==null){setState(()=>error='Profil fotoğrafı ekle.');return;}if(name.text.trim().length<3){setState(()=>error='Ad soyadını gir.');return;}if(birthDate==null){setState(()=>error='Doğum tarihini seç.');return;}setState((){busy=true;error=null;});try{final id=OpenBackend.instance.userId;if(id==null)throw StateError('Oturum bulunamadı');final bytes=await photo!.readAsBytes();final ext=photo!.name.toLowerCase().endsWith('.png')?'png':'jpg';final path='$id/avatar.$ext';await OpenBackend.instance.client.storage.from('avatars').uploadBinary(path,bytes,fileOptions:const FileOptions(upsert:true));final avatar='${OpenBackend.instance.client.storage.from('avatars').getPublicUrl(path)}?v=${DateTime.now().millisecondsSinceEpoch}';await OpenBackend.instance.saveProfile(name.text,'',gender);await OpenBackend.instance.client.from('profiles').update({'birth_date':'${birthDate!.year.toString().padLeft(4,'0')}-${birthDate!.month.toString().padLeft(2,'0')}-${birthDate!.day.toString().padLeft(2,'0')}','avatar_url':avatar}).eq('id',id);if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>const _LocationPermissionScreen()));}catch(e){if(mounted)setState(()=>error='Profil kaydedilemedi: $e');}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent),body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(26,4,26,32),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const ui.StepHeader(step:1,total:3),const SizedBox(height:24),const ui.PageTitle('Seni tanıyalım.','Profilin kilitli başlayacak. Temel bilgilerini ekle.'),const SizedBox(height:22),InkWell(onTap:busy?null:pickPhoto,borderRadius:BorderRadius.circular(30),child:Container(height:170,width:double.infinity,decoration:BoxDecoration(color:ui.OpenApp.soft,borderRadius:BorderRadius.circular(30),border:photo==null?null:Border.all(color:ui.OpenApp.lime,width:2)),child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(photo==null?Icons.add_a_photo_outlined:Icons.check_circle_rounded,size:52),const SizedBox(height:9),Text(photo==null?'Profil fotoğrafı ekle':'Profil fotoğrafı seçildi',style:const TextStyle(fontWeight:FontWeight.w800)),if(photo!=null)const Padding(padding:EdgeInsets.only(top:4),child:Text('Değiştirmek için dokun',style:TextStyle(color:ui.OpenApp.muted,fontSize:12)))])))),const SizedBox(height:16),TextField(controller:name,textCapitalization:TextCapitalization.words,decoration:const InputDecoration(labelText:'Ad Soyad',prefixIcon:Icon(Icons.person_outline_rounded))),const SizedBox(height:14),InkWell(onTap:pickBirth,borderRadius:BorderRadius.circular(22),child:InputDecorator(decoration:const InputDecoration(labelText:'Doğum tarihi / Yaş',prefixIcon:Icon(Icons.cake_outlined)),child:Text(birthDate==null?'Doğum tarihini seç':'${birthDate!.day.toString().padLeft(2,'0')}.${birthDate!.month.toString().padLeft(2,'0')}.${birthDate!.year}  ·  $age yaş'))),const SizedBox(height:18),const Text('Cinsiyet',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Wrap(spacing:8,runSpacing:8,children:['Kadın','Erkek','Belirtmek istemiyorum'].map((x)=>ChoiceChip(label:Text(x),selected:gender==x,selectedColor:ui.OpenApp.lime,onSelected:(_)=>setState(()=>gender=x))).toList()),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:const TextStyle(color:Colors.red,fontWeight:FontWeight.w600))),const SizedBox(height:26),FilledButton(onPressed:busy?null:next,child:Text(busy?'Profil oluşturuluyor...':'Devam et'))]))));}

class _LocationPermissionScreen extends StatefulWidget{const _LocationPermissionScreen();@override State<_LocationPermissionScreen> createState()=>_LocationPermissionScreenState();}
class _LocationPermissionScreenState extends State<_LocationPermissionScreen>{bool busy=false;String? error;Future<void> allow()async{if(busy)return;setState((){busy=true;error=null;});try{if(!await Geolocator.isLocationServiceEnabled()){setState(()=>error='Telefonunun konum servisini açıp tekrar dene.');return;}var permission=await Geolocator.checkPermission();if(permission==LocationPermission.denied)permission=await Geolocator.requestPermission();if(permission==LocationPermission.denied){setState(()=>error='Yakındaki kişileri gösterebilmemiz için konum izni gerekiyor.');return;}if(permission==LocationPermission.deniedForever){setState(()=>error='Konum izni kapalı. Telefon ayarlarından Open için konum iznini aç.');return;}final p=await Geolocator.getCurrentPosition(locationSettings:const LocationSettings(accuracy:LocationAccuracy.medium,timeLimit:Duration(seconds:15)));final id=OpenBackend.instance.userId;if(id==null)throw StateError('Oturum bulunamadı');await OpenBackend.instance.client.from('profiles').update({'latitude':p.latitude,'longitude':p.longitude}).eq('id',id);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const _QuestionsScreen()));}catch(e){if(mounted)setState(()=>error='Konum alınamadı. Tekrar dene.');}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(28,24,28,30),child:Column(children:[const Align(alignment:Alignment.centerLeft,child:ui.StepHeader(step:2,total:3)),const Spacer(),Container(width:132,height:132,decoration:const BoxDecoration(color:ui.OpenApp.lime,shape:BoxShape.circle),child:const Icon(Icons.near_me_rounded,size:64,color:ui.OpenApp.ink)),const SizedBox(height:34),const Text('Yakınındaki kişileri keşfet.',textAlign:TextAlign.center,style:TextStyle(fontSize:32,height:1.08,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Text('Open, sana yakın profilleri göstermek ve mesafeyi hesaplamak için konumunu kullanır. Tam adresin diğer kullanıcılara gösterilmez.',textAlign:TextAlign.center,style:TextStyle(fontSize:16,height:1.45,color:ui.OpenApp.muted)),if(error!=null)Padding(padding:const EdgeInsets.only(top:18),child:Text(error!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.red,fontWeight:FontWeight.w600))),const Spacer(),FilledButton.icon(onPressed:busy?null:allow,icon:const Icon(Icons.location_on_rounded),label:Text(busy?'Konum alınıyor...':'Konumuma izin ver')),const SizedBox(height:10),if(error!=null)TextButton(onPressed:()=>Geolocator.openAppSettings(),child:const Text('Uygulama ayarlarını aç',style:TextStyle(color:ui.OpenApp.ink,fontWeight:FontWeight.w700)))]))));}

class _QuestionsScreen extends StatefulWidget{const _QuestionsScreen();@override State<_QuestionsScreen> createState()=>_QuestionsScreenState();}
class _QuestionsScreenState extends State<_QuestionsScreen>{final selected=<int>{};bool busy=false;String? error;final questions=const ['Bir pazar sabahı seni nerede bulurum?','Seni güldüren küçük şey ne?','Birine hemen güvenmeni sağlayan şey?','Hayalindeki plansız gün nasıl geçer?','Bir şarkı seni hangi ana götürür?','İlk buluşmada en çok neye dikkat edersin?'];Future<void> finish()async{if(selected.length!=3)return;setState(()=>busy=true);try{final x=selected.toList()..sort();await OpenBackend.instance.saveLockQuestions(x.map((i)=>questions[i]).toList());if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>_shell()),(_)=>false);}catch(e){if(mounted)setState(()=>error='Sorular kaydedilemedi: $e');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent),body:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(26,4,26,28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const ui.StepHeader(step:3,total:3),const SizedBox(height:24),const ui.PageTitle('3 kilit sorunu seç.','Seni keşfetmek isteyen kişi önce bu sorulardan birini cevaplayacak.'),const SizedBox(height:18),Expanded(child:ListView.separated(itemCount:questions.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final active=selected.contains(i);return InkWell(onTap:()=>setState((){if(active){selected.remove(i);}else if(selected.length<3){selected.add(i);}}),borderRadius:BorderRadius.circular(22),child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:active?ui.OpenApp.lime.withValues(alpha:.16):ui.OpenApp.soft,borderRadius:BorderRadius.circular(22),border:Border.all(color:active?ui.OpenApp.lime:Colors.transparent,width:2)),child:Row(children:[Expanded(child:Text(questions[i],style:const TextStyle(fontWeight:FontWeight.w700))),ui.AppSvg(active?ui.AppIcons.unlock:ui.AppIcons.lock,size:28)])));})),if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),FilledButton(onPressed:selected.length==3&&!busy?finish:null,child:Text(busy?'Kaydediliyor...':selected.length==3?'Profili tamamla':'${selected.length}/3 soru seçildi'))]))));}
