import 'package:flutter/material.dart';

import 'data/open_backend.dart';
import 'main.dart' as ui;

class RealProfileScreen extends StatefulWidget {
  const RealProfileScreen({super.key, this.onSignedOut});
  final VoidCallback? onSignedOut;
  @override State<RealProfileScreen> createState()=>_RealProfileScreenState();
}

class _RealProfileScreenState extends State<RealProfileScreen>{
  bool busy=false,loading=true; Map<String,dynamic> profile=const {}; List<Map<String,dynamic>> questions=const []; int matchCount=0,keyCount=0;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{final id=OpenBackend.instance.userId;if(id==null)return;if(mounted)setState(()=>loading=true);try{final p=await OpenBackend.instance.client.from('profiles').select('id,display_name,birth_date,bio,city,avatar_url,is_online,is_verified').eq('id',id).maybeSingle();final q=await OpenBackend.instance.client.from('profile_questions').select('id,question,position').eq('profile_id',id).order('position');final m=await OpenBackend.instance.activeMatches();final k=await OpenBackend.instance.client.from('key_requests').select('id').eq('receiver_id',id);if(!mounted)return;setState((){profile=p==null?<String,dynamic>{}:Map<String,dynamic>.from(p);questions=List<Map<String,dynamic>>.from(q);matchCount=m.length;keyCount=List<dynamic>.from(k).length;});}finally{if(mounted)setState(()=>loading=false);}}
  int? _age(){final r=profile['birth_date']?.toString();if(r==null||r.isEmpty)return null;final b=DateTime.tryParse(r);if(b==null)return null;final n=DateTime.now();var a=n.year-b.year;if(n.month<b.month||(n.month==b.month&&n.day<b.day))a--;return a;}
  Future<void> _editQuestions()async{final cs=List.generate(3,(i)=>TextEditingController(text:i<questions.length?questions[i]['question']?.toString()??'':''));final saved=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,backgroundColor:Colors.white,shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(30))),builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(22,22,22,MediaQuery.of(c).viewInsets.bottom+24),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[const Expanded(child:Text('Sorularını düzenle',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900))),IconButton(onPressed:()=>Navigator.pop(c,false),icon:const Icon(Icons.close_rounded))]),for(var i=0;i<3;i++)TextField(controller:cs[i],maxLength:90,decoration:InputDecoration(labelText:'${i+1}. soru')),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>cs.any((x)=>x.text.trim().isEmpty)?null:Navigator.pop(c,true),child:const Text('Soruları kaydet')))])));if(saved==true){setState(()=>busy=true);try{await OpenBackend.instance.saveLockQuestions(cs.map((x)=>x.text.trim()).toList());await _load();}finally{if(mounted)setState(()=>busy=false);}}for(final c in cs)c.dispose();}
  Future<void> _signOut()async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Çıkış yapılsın mı?'),content:const Text('Hesabından çıkış yapacaksın. Tekrar giriş yapmak için e-posta veya telefonunu kullanabilirsin.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Çıkış yap'))]));if(ok==true){await OpenBackend.instance.signOut();if(mounted)widget.onSignedOut?.call();}}
  @override Widget build(BuildContext context){if(loading)return const SafeArea(child:Center(child:CircularProgressIndicator()));final name=(profile['display_name']??'Open kullanıcısı').toString(),city=(profile['city']??'').toString(),avatar=profile['avatar_url']?.toString();final hasAvatar=avatar!=null&&avatar.isNotEmpty,age=_age();return SafeArea(child:RefreshIndicator(onRefresh:_load,child:ListView(padding:EdgeInsets.zero,children:[
    Stack(clipBehavior:Clip.none,children:[
      ClipPath(clipper:_ProfileCurveClipper(),child:Container(padding:const EdgeInsets.fromLTRB(22,20,22,126),color:Colors.white,child:Column(children:[
        Row(children:[const _TopCircle(child:_Sparkles()),const Spacer(),_TopCircle(child:IconButton(onPressed:(){},icon:const Icon(Icons.settings_outlined)))]),const SizedBox(height:4),
        Stack(clipBehavior:Clip.none,children:[Container(width:188,height:188,padding:const EdgeInsets.all(5),decoration:BoxDecoration(shape:BoxShape.circle,color:Colors.white,boxShadow:[BoxShadow(color:ui.OpenApp.lime.withValues(alpha:.20),blurRadius:38,spreadRadius:7)]),child:CircleAvatar(backgroundColor:ui.OpenApp.soft,backgroundImage:hasAvatar?NetworkImage(avatar):null,child:hasAvatar?null:const Icon(Icons.person_rounded,size:82))),Positioned(right:3,bottom:8,child:Container(width:54,height:54,decoration:BoxDecoration(color:ui.OpenApp.lime,shape:BoxShape.circle,border:Border.all(color:Colors.white,width:4)),child:const Icon(Icons.camera_alt_outlined)))]),
        const SizedBox(height:18),Row(mainAxisSize:MainAxisSize.min,children:[Flexible(child:Text('$name${age==null?'':', $age'}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:34,fontWeight:FontWeight.w900,letterSpacing:-1))),if(profile['is_verified']==true)...[const SizedBox(width:7),const Icon(Icons.verified_rounded,color:ui.OpenApp.lime,size:24)]]),const SizedBox(height:10),Text('${city.isEmpty?'Konum ekle':city}  ·  ${profile['is_online']==true?'Aktif':'Profilin'}',style:const TextStyle(color:ui.OpenApp.muted,fontSize:15)),
        const SizedBox(height:28),Row(mainAxisAlignment:MainAxisAlignment.center,children:[_RoundAction(icon:Icons.settings_outlined,label:'Ayarlar',onTap:(){}),const SizedBox(width:34),_RoundAction(icon:Icons.add_a_photo_outlined,label:'Medya Ekle',large:true,onTap:(){}),const SizedBox(width:34),_RoundAction(icon:Icons.shield_outlined,label:'Güvenlik',onTap:(){})])
      ]))),
      Positioned(left:0,right:0,bottom:-29,child:Center(child:Container(width:62,height:62,decoration:BoxDecoration(color:Colors.white,shape:BoxShape.circle,boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.08),blurRadius:20,offset:const Offset(0,6))]),child:const Center(child:_Sparkles(size:31))))),
    ]),
    const SizedBox(height:58),
    Padding(padding:const EdgeInsets.symmetric(horizontal:22),child:Container(padding:const EdgeInsets.fromLTRB(18,18,18,20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(30),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.055),blurRadius:25,offset:const Offset(0,8))]),child:Column(children:[
      Row(children:[const Text('Soruların',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(width:8),const _Sparkles(size:27),const Spacer(),TextButton.icon(onPressed:busy?null:_editQuestions,icon:const Icon(Icons.edit_outlined,size:19),label:const Text('Düzenle'))]),
      if(questions.isEmpty)TextButton(onPressed:_editQuestions,child:const Text('3 kilit sorunu oluştur'))else for(var i=0;i<questions.length;i++)Padding(padding:const EdgeInsets.only(top:10),child:_QuestionTile(question:questions[i]['question']?.toString()??'',onEdit:_editQuestions))
    ]))),
    const SizedBox(height:16),Padding(padding:const EdgeInsets.symmetric(horizontal:22),child:Row(children:[Expanded(child:_StatCard(icon:Icons.people_alt_outlined,label:'Eşleşme',value:'$matchCount')),const SizedBox(width:9),Expanded(child:_StatCard(icon:Icons.key_outlined,label:'Anahtarlar',value:'$keyCount')),const SizedBox(width:9),const Expanded(child:_StatCard(icon:Icons.trending_up_rounded,label:'Cevap Oranı',value:'—'))])),TextButton.icon(onPressed:_signOut,icon:const Icon(Icons.logout_rounded),label:const Text('Çıkış yap'),style:TextButton.styleFrom(foregroundColor:Colors.red))
  ])));}
}
class _ProfileCurveClipper extends CustomClipper<Path>{@override Path getClip(Size s){final p=Path()..lineTo(0,s.height-118);p.cubicTo(s.width*.18,s.height-56,s.width*.34,s.height-28,s.width*.50,s.height-24);p.cubicTo(s.width*.66,s.height-28,s.width*.82,s.height-56,s.width,s.height-118);p.lineTo(s.width,0);p.close();return p;}@override bool shouldReclip(covariant CustomClipper<Path> oldClipper)=>false;}
class _Sparkles extends StatelessWidget{const _Sparkles({this.size=26});final double size;@override Widget build(BuildContext c)=>SizedBox(width:size,height:size,child:Stack(children:[Positioned(left:0,top:size*.26,child:Icon(Icons.auto_awesome_rounded,color:ui.OpenApp.lime,size:size*.72)),Positioned(right:0,top:0,child:Icon(Icons.star_rounded,color:ui.OpenApp.lime,size:size*.30)),Positioned(right:size*.05,bottom:0,child:Icon(Icons.star_rounded,color:ui.OpenApp.lime,size:size*.25))]));}
class _TopCircle extends StatelessWidget{const _TopCircle({required this.child});final Widget child;@override Widget build(BuildContext c)=>Container(width:46,height:46,alignment:Alignment.center,decoration:BoxDecoration(color:Colors.white,shape:BoxShape.circle,boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.07),blurRadius:16)]),child:child);}
class _RoundAction extends StatelessWidget{const _RoundAction({required this.icon,required this.label,required this.onTap,this.large=false});final IconData icon;final String label;final VoidCallback onTap;final bool large;@override Widget build(BuildContext c)=>Column(children:[InkWell(onTap:onTap,borderRadius:BorderRadius.circular(60),child:Container(width:large?92:64,height:large?92:64,decoration:BoxDecoration(color:large?ui.OpenApp.lime:Colors.white,shape:BoxShape.circle,boxShadow:[BoxShadow(color:(large?ui.OpenApp.lime:Colors.black).withValues(alpha:large?.24:.07),blurRadius:24)]),child:Icon(icon,size:large?39:28))),const SizedBox(height:8),Text(label,style:TextStyle(fontSize:large?16:13,fontWeight:large?FontWeight.w800:FontWeight.w600))]);}
class _QuestionTile extends StatelessWidget{const _QuestionTile({required this.question,required this.onEdit});final String question;final VoidCallback onEdit;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:13),decoration:BoxDecoration(color:ui.OpenApp.soft,borderRadius:BorderRadius.circular(23)),child:Row(children:[Container(width:50,height:50,alignment:Alignment.center,decoration:BoxDecoration(color:Colors.white,shape:BoxShape.circle,boxShadow:[BoxShadow(color:ui.OpenApp.lime.withValues(alpha:.20),blurRadius:10)]),child:const _Sparkles(size:28)),const SizedBox(width:12),Expanded(child:Text(question,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w800,height:1.25))),IconButton(onPressed:onEdit,icon:const Icon(Icons.edit_outlined,size:21))]));}
class _StatCard extends StatelessWidget{const _StatCard({required this.icon,required this.label,required this.value});final IconData icon;final String label,value;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.045),blurRadius:18)]),child:Row(children:[Container(width:36,height:36,decoration:BoxDecoration(color:ui.OpenApp.lime.withValues(alpha:.18),shape:BoxShape.circle),child:Icon(icon,size:20)),const SizedBox(width:7),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,maxLines:1,style:const TextStyle(fontSize:10,color:ui.OpenApp.muted)),Text(value,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))]))]));}