import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'data/open_backend.dart';
import 'main.dart' as ui;
import 'enhanced_social_ui.dart' show EnhancedChatScreen;

class RealKeysScreen extends StatelessWidget{const RealKeysScreen({super.key});@override Widget build(BuildContext context)=>const SizedBox.shrink();}
class RealMatchScreen extends StatefulWidget{const RealMatchScreen({super.key,required this.matchId,required this.otherProfile});final String matchId;final Map<String,dynamic> otherProfile;@override State<RealMatchScreen> createState()=>_RealMatchScreenState();}
class _RealMatchScreenState extends State<RealMatchScreen> with TickerProviderStateMixin{late final AnimationController introController,confettiController;bool unlocked=false;Map<String,dynamic> myProfile={};@override void initState(){super.initState();introController=AnimationController(vsync:this,duration:const Duration(milliseconds:1200))..forward();confettiController=AnimationController(vsync:this,duration:const Duration(seconds:3))..repeat();_loadMine();Future.delayed(const Duration(milliseconds:600),(){if(mounted)setState(()=>unlocked=true);});}Future<void> _loadMine()async{final id=OpenBackend.instance.userId;if(id==null)return;final p=await OpenBackend.instance.client.from('profiles').select('id,display_name,avatar_url').eq('id',id).maybeSingle();if(mounted&&p!=null)setState(()=>myProfile=Map<String,dynamic>.from(p));}@override void dispose(){introController.dispose();confettiController.dispose();super.dispose();}@override Widget build(BuildContext context){final other=(widget.otherProfile['display_name']??'Yeni eşleşme').toString();return Scaffold(backgroundColor:Colors.white,body:SafeArea(child:Stack(children:[Positioned.fill(child:AnimatedBuilder(animation:confettiController,builder:(_,__)=>CustomPaint(painter:_CelebrationPainter(confettiController.value)))),Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Spacer(),const Text('İlk kilit açıldı!',textAlign:TextAlign.center,style:TextStyle(fontSize:40,fontWeight:FontWeight.w900,letterSpacing:-1.5)),const SizedBox(height:12),const Text('Birbirinizi tanımak için 15 dakikanız var.',textAlign:TextAlign.center,style:TextStyle(fontSize:17,color:ui.OpenApp.muted)),const Spacer(),Row(mainAxisAlignment:MainAxisAlignment.center,children:[_MatchAvatar(profile:myProfile),const SizedBox(width:10),AnimatedContainer(duration:const Duration(milliseconds:400),width:82,height:82,decoration:BoxDecoration(color:ui.OpenApp.lime,borderRadius:BorderRadius.circular(26)),child:Icon(unlocked?Icons.lock_open_rounded:Icons.lock_rounded,size:48)),const SizedBox(width:10),_MatchAvatar(profile:widget.otherProfile)]),const SizedBox(height:22),Text('$other ile 1/3 anahtar açıldı 🔑',style:const TextStyle(fontWeight:FontWeight.w900)),const Spacer(),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{await OpenBackend.instance.startTrialChat(widget.matchId);if(!context.mounted)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>EnhancedChatScreen(matchId:widget.matchId,profile:widget.otherProfile)));},child:const Text('15 dk ilk sohbeti başlat ⏱️'))),const SizedBox(height:10),SizedBox(width:double.infinity,child:OutlinedButton(onPressed:()=>Navigator.pop(context),child:const Text('Daha sonra'))),const Spacer()])),])));}}
class _MatchAvatar extends StatelessWidget{const _MatchAvatar({required this.profile});final Map<String,dynamic> profile;@override Widget build(BuildContext context){final a=profile['avatar_url']?.toString(),has=a!=null&&a.isNotEmpty;return CircleAvatar(radius:50,backgroundColor:ui.OpenApp.soft,backgroundImage:has?NetworkImage(a):null,child:has?null:const Icon(Icons.person_rounded,size:44));}}
class _CelebrationPainter extends CustomPainter{_CelebrationPainter(this.progress);final double progress;@override void paint(Canvas canvas,Size size){final p=Paint()..color=ui.OpenApp.lime.withValues(alpha:.55);for(var i=0;i<12;i++){final x=size.width*((i*37%100)/100),y=size.height*((i*61%100)/100)+math.sin(progress*math.pi*2+i)*8;canvas.drawCircle(Offset(x,y),2.5,p);}}@override bool shouldRepaint(covariant _CelebrationPainter old)=>old.progress!=progress;}
class RealMessagesScreen extends StatelessWidget{const RealMessagesScreen({super.key});@override Widget build(BuildContext context)=>const SizedBox.shrink();}
class RealChatScreen extends StatelessWidget{const RealChatScreen({super.key,required this.matchId,required this.profile});final String matchId;final Map<String,dynamic> profile;@override Widget build(BuildContext context)=>EnhancedChatScreen(matchId:matchId,profile:profile);}
