import 'package:flutter/material.dart';
import 'data/open_backend.dart';
import 'main.dart' as ui;

class SettingsScreen extends StatefulWidget{const SettingsScreen({super.key,this.onSignedOut});final VoidCallback? onSignedOut;@override State<SettingsScreen> createState()=>_SettingsScreenState();}
class _SettingsScreenState extends State<SettingsScreen>{
Map<String,dynamic> p={};bool loading=true;String lookingFor='Herkes',language='Türkçe',theme='Açık',city='';int minAge=18,maxAge=45,distance=50;bool keyN=true,matchN=true,msgN=true,haptics=true,paused=false;
@override void initState(){super.initState();_load();}
Future<void> _load()async{final id=OpenBackend.instance.userId;if(id==null)return;final c=OpenBackend.instance.client;final profile=await c.from('profiles').select().eq('id',id).single();final rows=await c.from('user_settings').select().eq('user_id',id).limit(1);final s=rows.isEmpty?<String,dynamic>{}:Map<String,dynamic>.from(rows.first);if(!mounted)return;setState((){p=Map<String,dynamic>.from(profile);paused=p['account_paused']??false;lookingFor=(s['looking_for']??p['looking_for']??'Herkes').toString();minAge=s['min_age']??18;maxAge=s['max_age']??45;distance=s['max_distance_km']??50;city=(s['discover_city']??p['city']??'').toString();keyN=s['notify_keys']??true;matchN=s['notify_matches']??true;msgN=s['notify_messages']??true;language=(s['app_language']??'Türkçe').toString();theme=(s['app_theme']??'Açık').toString();haptics=s['haptics']??true;loading=false;});}
Future<void> _saveSettings(Map<String,dynamic> data)async{final id=OpenBackend.instance.userId;if(id==null)return;await OpenBackend.instance.client.from('user_settings').upsert({'user_id':id,...data,'updated_at':DateTime.now().toIso8601String()});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Kaydedildi')));}
Future<void> _saveProfile(Map<String,dynamic> data)async{final id=OpenBackend.instance.userId;if(id==null)return;await OpenBackend.instance.client.from('profiles').update(data).eq('id',id);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Kaydedildi')));}
Future<String?> _text(String title,String initial)async{final c=TextEditingController(text:initial);final r=await showDialog<String>(context:context,builder:(x)=>AlertDialog(title:Text(title),content:TextField(controller:c,autofocus:true,maxLength:2000),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,c.text.trim()),child:const Text('Kaydet'))]));c.dispose();return r;}
Future<void> _choice(String title,List<String> values,String current,Future<void> Function(String) save)async{final v=await showModalBottomSheet<String>(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[Padding(padding:const EdgeInsets.all(16),child:Text(title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900))),...values.map((e)=>ListTile(title:Text(e),trailing:e==current?const Icon(Icons.check_circle_rounded):null,onTap:()=>Navigator.pop(x,e))),const SizedBox(height:12)])));if(v!=null)await save(v);}
Future<void> _age()async{var lo=minAge.toDouble(),hi=maxAge.toDouble();final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setLocal)=>AlertDialog(title:const Text('Yaş aralığı'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('${lo.round()} – ${hi.round()} yaş',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),RangeSlider(values:RangeValues(lo,hi),min:18,max:80,divisions:62,onChanged:(v)=>setLocal((){lo=v.start;hi=v.end;}))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Kaydet'))])));if(ok==true){setState((){minAge=lo.round();maxAge=hi.round();});await _saveSettings({'min_age':minAge,'max_age':maxAge});}}
Future<void> _distance()async{var d=distance.toDouble();final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setLocal)=>AlertDialog(title:const Text('Maksimum mesafe'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('${d.round()} km',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Slider(value:d,min:1,max:200,divisions:199,onChanged:(v)=>setLocal(()=>d=v))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Kaydet'))])));if(ok==true){setState(()=>distance=d.round());await _saveSettings({'max_distance_km':distance});}}
Future<void> _account()async{final name=await _text('Adın',(p['display_name']??'').toString());if(name!=null&&name.isNotEmpty){setState(()=>p={...p,'display_name':name});await _saveProfile({'display_name':name});}}
Future<void> _pause()async{final next=!paused;final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:Text(next?'Hesabı dondur?':'Hesabı yeniden aç?'),content:Text(next?'Profilin Keşfet’te gösterilmeyecek.':'Profilin yeniden aktif olacak.'),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:Text(next?'Dondur':'Aktif et'))]));if(ok==true){setState(()=>paused=next);await _saveProfile({'account_paused':next});}}
Future<void> _feedback()async{final v=await _text('Geri bildirim','');final id=OpenBackend.instance.userId;if(v!=null&&v.isNotEmpty&&id!=null){await OpenBackend.instance.client.from('feedback').insert({'user_id':id,'body':v});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Geri bildirimin gönderildi. Teşekkürler.')));}}
Future<void> _signOut()async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Çıkış yapılsın mı?'),content:const Text('Hesabından çıkış yapacaksın.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Çıkış yap'))]));if(ok==true){await OpenBackend.instance.signOut();if(!mounted)return;widget.onSignedOut?.call();Navigator.of(context).popUntil((r)=>r.isFirst);}}
Future<void> _delete()async{final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('Hesabımı sil'),content:const Text('Profil, ayarlar ve uygulama verilerin silinecek. Devam edilsin mi?'),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red),onPressed:()=>Navigator.pop(x,true),child:const Text('Verilerimi sil'))]));if(ok==true){final id=OpenBackend.instance.userId;if(id!=null){await OpenBackend.instance.client.from('user_settings').delete().eq('user_id',id);await OpenBackend.instance.client.from('profiles').delete().eq('id',id);}await OpenBackend.instance.signOut();if(!mounted)return;widget.onSignedOut?.call();Navigator.of(context).popUntil((r)=>r.isFirst);}}
void _info(String title,String body)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>_InfoPage(title:title,body:body)));
@override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(backgroundColor:const Color(0xfff7f7f4),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,12,18,32),children:[
Row(children:[_circle(Icons.arrow_back_rounded,()=>Navigator.pop(context)),const Expanded(child:Text('Ayarlar',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.w900,letterSpacing:-.8))),const SizedBox(width:48)]),const SizedBox(height:24),
_Section(title:'Hesap',children:[_Tile(Icons.person_outline_rounded,'Hesap bilgileri',(p['display_name']??'Profil bilgilerin').toString(),_account),_Tile(Icons.pause_circle_outline_rounded,paused?'Hesabı yeniden aç':'Hesabı dondur',paused?'Profilin şu anda gizli':'Profilini geçici olarak gizle',_pause)]),
_Section(title:'Keşfet tercihleri',children:[_Tile(Icons.tune_rounded,'Aradığın kişiler',lookingFor,()=>_choice('Aradığın kişiler',['Kadınlar','Erkekler','Herkes'],lookingFor,(v)async{setState(()=>lookingFor=v);await _saveSettings({'looking_for':v});})),_Tile(Icons.cake_outlined,'Yaş aralığı','$minAge – $maxAge',_age),_Tile(Icons.near_me_outlined,'Maksimum mesafe','$distance km',_distance),_Tile(Icons.location_on_outlined,'Konum',city.isEmpty?'Konum ekle':city,()async{final v=await _text('Keşfet konumu',city);if(v!=null&&v.isNotEmpty){setState(()=>city=v);await _saveSettings({'discover_city':v});}})]),
_Section(title:'Bildirimler',children:[_SwitchTile(Icons.key_outlined,'Yeni anahtarlar',keyN,(v){setState(()=>keyN=v);_saveSettings({'notify_keys':v});}),_SwitchTile(Icons.auto_awesome_rounded,'Eşleşmeler',matchN,(v){setState(()=>matchN=v);_saveSettings({'notify_matches':v});}),_SwitchTile(Icons.chat_bubble_outline_rounded,'Mesajlar',msgN,(v){setState(()=>msgN=v);_saveSettings({'notify_messages':v});})]),
_Section(title:'Uygulama',children:[_Tile(Icons.language_rounded,'Dil',language,()=>_choice('Dil',['Türkçe','English'],language,(v)async{setState(()=>language=v);await _saveSettings({'app_language':v});})),_Tile(Icons.dark_mode_outlined,'Görünüm',theme,()=>_choice('Görünüm',['Açık','Koyu','Sistem'],theme,(v)async{setState(()=>theme=v);await _saveSettings({'app_theme':v});})),_SwitchTile(Icons.vibration_rounded,'Titreşim ve ses',haptics,(v){setState(()=>haptics=v);_saveSettings({'haptics':v});})]),
_Section(title:'Destek',children:[_Tile(Icons.help_outline_rounded,'Yardım ve destek','Sık sorulan sorular',()=>_info('Yardım ve destek','Open’da profil, anahtar, eşleşme ve mesajlaşma hakkında yardım içerikleri burada yer alır. Güvenlikle ilgili durumlarda Güvenlik Merkezi’ni kullanabilirsin.')),_Tile(Icons.feedback_outlined,'Geri bildirim','Görüşünü bize ilet',_feedback),_Tile(Icons.description_outlined,'Kullanım koşulları','',()=>_info('Kullanım koşulları','Open’ı kullanırken diğer kullanıcılara saygılı davranmalı, yanıltıcı profil oluşturmamalı ve güvenlik kurallarına uymalısın. Üretim sürümünde hukuki kullanım koşulları bu alanda yayınlanacaktır.')),_Tile(Icons.privacy_tip_outlined,'Gizlilik politikası','',()=>_info('Gizlilik politikası','Open; hesabın, profilin, eşleşmelerin ve uygulama tercihlerin için gerekli verileri kullanır. Üretim sürümünde ayrıntılı yasal gizlilik politikası bu alanda yayınlanacaktır.'))]),
const SizedBox(height:4),SizedBox(height:58,child:OutlinedButton.icon(onPressed:_signOut,icon:const Icon(Icons.logout_rounded),label:const Text('Çıkış yap',style:TextStyle(fontWeight:FontWeight.w800)),style:OutlinedButton.styleFrom(foregroundColor:Colors.red,side:BorderSide(color:Colors.red.withValues(alpha:.18)),backgroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20))))),const SizedBox(height:14),TextButton(onPressed:_delete,child:const Text('Hesabımı sil',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w700))),const Center(child:Text('Open',style:TextStyle(color:ui.OpenApp.muted,fontSize:12)))
])));}
Widget _circle(IconData icon,VoidCallback tap)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(30),child:Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white,shape:BoxShape.circle,boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.06),blurRadius:14)]),child:Icon(icon)));
}
class _Section extends StatelessWidget{const _Section({required this.title,required this.children});final String title;final List<Widget> children;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Padding(padding:const EdgeInsets.fromLTRB(6,0,6,9),child:Text(title,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900))),Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(25),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.035),blurRadius:18)]),child:Column(children:[for(var i=0;i<children.length;i++)...[children[i],if(i<children.length-1)const Divider(height:1,indent:64,endIndent:16)]]))]));}
class _Tile extends StatelessWidget{const _Tile(this.icon,this.title,this.subtitle,this.tap);final IconData icon;final String title,subtitle;final VoidCallback tap;@override Widget build(BuildContext c)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(22),child:Padding(padding:const EdgeInsets.symmetric(horizontal:14,vertical:13),child:Row(children:[_SettingIcon(icon),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w800)),if(subtitle.isNotEmpty)...[const SizedBox(height:2),Text(subtitle,style:const TextStyle(fontSize:12,color:ui.OpenApp.muted))]])),const Icon(Icons.chevron_right_rounded,color:ui.OpenApp.muted)])));}
class _SwitchTile extends StatelessWidget{const _SwitchTile(this.icon,this.title,this.value,this.changed);final IconData icon;final String title;final bool value;final ValueChanged<bool> changed;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(horizontal:14,vertical:10),child:Row(children:[_SettingIcon(icon),const SizedBox(width:12),Expanded(child:Text(title,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w800))),Switch(value:value,onChanged:changed,activeThumbColor:Colors.black,activeTrackColor:ui.OpenApp.lime)]));}
class _SettingIcon extends StatelessWidget{const _SettingIcon(this.icon);final IconData icon;@override Widget build(BuildContext c)=>Container(width:38,height:38,decoration:BoxDecoration(color:ui.OpenApp.lime.withValues(alpha:.16),shape:BoxShape.circle),child:Icon(icon,size:20,color:Colors.black));}
class _InfoPage extends StatelessWidget{const _InfoPage({required this.title,required this.body});final String title,body;@override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xfff7f7f4),appBar:AppBar(backgroundColor:const Color(0xfff7f7f4),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w900))),body:Padding(padding:const EdgeInsets.all(22),child:Container(width:double.infinity,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(26)),child:Text(body,style:const TextStyle(fontSize:16,height:1.55)))));}
